server:
  port: 3306

spring:
  application:
    name: home_service
  datasource:
    url: jdbc:mysql://localhost/hogar360
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update